module.exports = {
    INITIAL : 1,
    CAPACITY_DECLARED: 2,
    ENTITLEMENTS_PUBLISHED: 3,
    REQUISITIONS_PUBLISHED: 4,
    PROVISIONAL_SCHEDULE_PUBLISHED: 5,
    REVISIONS_PUBLISHED: 6,
    FINAL_SCHEDULE_PUBLISHED: 7
}